### ISSUE TITLE
Error with `replit user`

### ISSUE THREAD

**Issue by dbarnes18** [CoolCoderSJ/replit-cli#7]
Operating System: `macOS 10.15.7`
Shell: `zsh 5.7.1 (x86_64-apple-darwin19.0)`
Python: `Python 3.9.1`

```zsh
dillonbarnes@Downstairs-iMac ~ % replit user DillonB07
Traceback (most recent call last):
  File "/Users/dillonbarnes/Library/Python/3.9/bin/replit", line 5, in <module>
    from repl_cli.main import app
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/repl_cli/main.py", line 583, in <module>
    app()
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/dillonbarnes/Library/Python/3.9/lib/python/site-packages/repl_cli/main.py", line 553, in user
    icon = r['icon']['url']
TypeError: 'NoneType' object is not subscriptable
```

Video: https://youtu.be/1apEKasLAzA 
~*This is still processing as I am writing this, so it may be awful video quality for about an hour after this is posted.*~

**Comment by dbarnes18** [comment]
The issue was that my avatar was from gravatar. Changing it worked fine!

**Comment by CoolCoderSJ** [comment]
Yep the issue is when there isn't a custom profile picture present.
I'm on break right now which is why I haven't fixed it yet as I'm focusing on any major issues, I'll fix it later when I have time.
